// File generated by ArduinoML (C/yacc/lex)

#define SILENT LOW
#define CONTINUE HIGH
#define SHORT 1000
#define LONG 3000

long time = 0;
long debounce = 200;

int buzzer = 9;
int led = 8;
int button2 = 10;
int button1 = 11;

void setup() {
  pinMode(buzzer, OUTPUT);
  pinMode(led, OUTPUT);
  pinMode(button2, INPUT);
  pinMode(button1, INPUT);
}

void do_action(int actuator, int act_signal, boolean guard) {
  if (!guard) return;
  if (act_signal == SILENT || act_signal == CONTINUE) {
    digitalWrite(actuator, act_signal);
  } else {
    digitalWrite(actuator, HIGH);
    delay(act_signal);
    digitalWrite(actuator, LOW);
  }
}

void state_on(boolean act_guard) {
  do_action(led, CONTINUE, act_guard);
  do_action(buzzer, SHORT, act_guard);
  boolean guard =  millis() - time > debounce;
  if (digitalRead(button1) == LOW && guard) {
    time = millis();
    state_off(true);
  } else if (digitalRead(button2) == LOW && guard) {
    time = millis();
    state_off(true);
  } else  {
    state_on(false);
  }
}

void state_off(boolean act_guard) {
  do_action(led, SILENT, act_guard);
  do_action(buzzer, SILENT, act_guard);
  boolean guard =  millis() - time > debounce;
  if (digitalRead(button1) == HIGH && digitalRead(button2) == HIGH && guard) {
    time = millis();
    state_on(true);
  } else  {
    state_off(false);
  }
}

void loop() {
  state_off(true);
}
